[package]
name = "retro-junk-catalog"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_yml = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
