[package]
name = "retro-junk-nintendo"
version.workspace = true
edition.workspace = true

[dependencies]
retro-junk-core.workspace = true
thiserror.workspace = true
sha2.workspace = true
crc32fast.workspace = true
