[package]
name = "retro-junk-sony"
version.workspace = true
edition.workspace = true

[dependencies]
retro-junk-core.workspace = true
thiserror.workspace = true
chd.workspace = true
crc32fast.workspace = true
sha1.workspace = true
md5.workspace = true
log.workspace = true
